"""Seed a local PolicyInsight database with demo data.

This script is intentionally development-only. It creates a demo system admin,
a demo customer, imports the sample vendor configs, runs analysis, and seeds
default report templates. It does not contact any firewall.
"""
from __future__ import annotations

import argparse
import sys
import uuid
from pathlib import Path


BACKEND_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_DIR.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.analysis.engine import run_analysis  # noqa: E402
from app.api.upload import _refresh_customer_counters  # noqa: E402
from app.database import SessionLocal  # noqa: E402
from app.models.customer import Customer  # noqa: E402
from app.models.policy import FirewallObject, FirewallPolicy, FirewallRule  # noqa: E402
from app.models.user import ROLE_SYSTEM_ADMIN, User  # noqa: E402
from app.parsers import get_parser  # noqa: E402
from app.reporting.defaults import ensure_default_templates  # noqa: E402
from app.security.passwords import hash_password, validate_password_policy  # noqa: E402


DEFAULT_EMAIL = "demo@policyinsight.local"
DEFAULT_PASSWORD = "PolicyInsightDemo!2026"
DEFAULT_CUSTOMER = "Demo Customer"

SAMPLES = [
    ("FortiGate", "fortigate_sample.conf", "FGT-DEMO-01", "Default"),
    ("CheckPoint", "checkpoint_sample.json", "CP-DEMO-01", "Standard"),
    ("PaloAlto", "paloalto_sample.xml", "PAN-DEMO-01", "Panorama"),
    ("CiscoASA", "ciscoasa_sample.txt", "ASA-DEMO-01", "running-config"),
    ("HuaweiUSG", "huawei_sample.txt", "HW-USG-DEMO-01", "security-policy"),
]


def _get_or_create_user(db, email: str, password: str) -> User:
    user = db.query(User).filter(User.email == email).first()
    if user:
        print(f"User exists: {email}")
        return user
    validate_password_policy(password)
    user = User(
        id=str(uuid.uuid4()),
        email=email,
        full_name="PolicyInsight Demo Admin",
        password_hash=hash_password(password),
        role=ROLE_SYSTEM_ADMIN,
        is_active=True,
    )
    db.add(user)
    db.commit()
    print(f"Created demo admin: {email}")
    return user


def _get_or_create_customer(db, name: str) -> Customer:
    customer = db.query(Customer).filter(Customer.name == name).first()
    if customer:
        print(f"Customer exists: {name}")
        return customer
    customer = Customer(
        id=str(uuid.uuid4()),
        name=name,
        description="Local development tenant seeded from sample firewall configs.",
        contact_name="Demo Security Team",
        contact_email="security@example.local",
        industry="Technology",
        tags="demo,local-dev,sample-data",
        notes="Generated by backend/scripts/seed_demo.py.",
    )
    db.add(customer)
    db.commit()
    print(f"Created customer: {name}")
    return customer


def _sample_content(filename: str) -> str:
    path = REPO_ROOT / "sample_data" / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing sample file: {path}")
    return path.read_text(encoding="utf-8", errors="replace")


def _policy_exists(db, customer_id: str, filename: str) -> bool:
    return db.query(FirewallPolicy.id).filter(
        FirewallPolicy.customer_id == customer_id,
        FirewallPolicy.original_filename == filename,
    ).first() is not None


def _delete_existing_policy(db, customer_id: str, filename: str) -> None:
    rows = db.query(FirewallPolicy).filter(
        FirewallPolicy.customer_id == customer_id,
        FirewallPolicy.original_filename == filename,
    ).all()
    for row in rows:
        db.delete(row)
    if rows:
        db.commit()
        print(f"Removed {len(rows)} existing demo policy row(s) for {filename}")


def _persist_policy(db, customer: Customer, user: User, vendor: str, filename: str, firewall_name: str, package: str) -> None:
    rules, objects, warnings = get_parser(vendor).parse(_sample_content(filename))
    if not rules and not objects:
        print(f"Skipped {filename}: parser returned no rules or objects. Warnings: {warnings}")
        return

    policy = FirewallPolicy(
        id=str(uuid.uuid4()),
        customer_id=customer.id,
        firewall_name=firewall_name,
        vendor=vendor,
        policy_package=package,
        uploaded_by=user.email,
        original_filename=filename,
        file_path=str(REPO_ROOT / "sample_data" / filename),
        analysis_status="pending",
        rule_count=len(rules),
        object_count=len(objects),
        notes="Seeded from sample_data for local development.",
    )
    db.add(policy)
    db.flush()

    db.add_all([
        FirewallRule(
            id=str(uuid.uuid4()),
            policy_id=policy.id,
            vendor=vendor,
            firewall_name=firewall_name,
            policy_package=package,
            rule_id=str(rule.get("rule_id", "")),
            rule_uid=rule.get("rule_uid", ""),
            rule_number=rule.get("rule_number", 0),
            rule_name=rule.get("rule_name", ""),
            section=rule.get("section", ""),
            source_interfaces=rule.get("source_interfaces", []),
            destination_interfaces=rule.get("destination_interfaces", []),
            sources=rule.get("sources", []),
            destinations=rule.get("destinations", []),
            services=rule.get("services", []),
            applications=rule.get("applications", []),
            users=rule.get("users", []),
            vpn=rule.get("vpn", []),
            action=rule.get("action", ""),
            schedule=rule.get("schedule", ""),
            enabled=rule.get("enabled", True),
            logging_enabled=rule.get("logging_enabled", True),
            nat_enabled=rule.get("nat_enabled", False),
            comments=rule.get("comments", ""),
            hit_count=rule.get("hit_count"),
            last_hit=str(rule.get("last_hit")) if rule.get("last_hit") else None,
            first_hit=str(rule.get("first_hit")) if rule.get("first_hit") else None,
            install_on=rule.get("install_on", []),
            raw_data=rule.get("raw_data", {}),
        )
        for rule in rules
    ])
    db.add_all([
        FirewallObject(
            id=str(uuid.uuid4()),
            policy_id=policy.id,
            vendor=vendor,
            object_uid=obj.get("object_uid", ""),
            object_name=obj.get("object_name", ""),
            object_type=obj.get("object_type", "host"),
            value=obj.get("value", ""),
            protocol=obj.get("protocol"),
            port_start=obj.get("port_start"),
            port_end=obj.get("port_end"),
            members=obj.get("members", []),
            comment=obj.get("comment", ""),
            raw_data=obj.get("raw_data", {}),
        )
        for obj in objects
    ])
    db.commit()
    run_analysis(policy.id, db)
    print(f"Imported {vendor}: {len(rules)} rules, {len(objects)} objects, {len(warnings)} parser warning(s)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Seed local PolicyInsight demo data.")
    parser.add_argument("--email", default=DEFAULT_EMAIL, help="Demo admin email.")
    parser.add_argument("--password", default=DEFAULT_PASSWORD, help="Demo admin password.")
    parser.add_argument("--customer", default=DEFAULT_CUSTOMER, help="Demo customer name.")
    parser.add_argument("--replace", action="store_true", help="Replace existing demo policies seeded from sample files.")
    args = parser.parse_args()

    db = SessionLocal()
    try:
        user = _get_or_create_user(db, args.email, args.password)
        customer = _get_or_create_customer(db, args.customer)
        created_templates = ensure_default_templates(db)
        if created_templates:
            print(f"Created {created_templates} default report template(s)")

        for vendor, filename, firewall_name, package in SAMPLES:
            if args.replace:
                _delete_existing_policy(db, customer.id, filename)
            elif _policy_exists(db, customer.id, filename):
                print(f"Policy exists, skipping: {filename} (use --replace to reimport)")
                continue
            _persist_policy(db, customer, user, vendor, filename, firewall_name, package)

        _refresh_customer_counters(customer.id, db)
        print("")
        print("Demo seed complete.")
        print(f"Login:    {args.email}")
        print(f"Password: {args.password}")
        print("Open:     http://localhost:3000")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    raise SystemExit(main())
