"""reporting templates and generated reports

Revision ID: b679ae30d172
Revises: 8b6c4d2e9a10
Create Date: 2026-06-20 13:32:38.868892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b679ae30d172'
down_revision: Union[str, None] = '8b6c4d2e9a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('analysis_run_id', sa.String(), nullable=True),
    sa.Column('firewall_name', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('export_format', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('selected_sections', sa.JSON(), nullable=True),
    sa.Column('selected_finding_categories', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_reports_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_policy_id'), ['policy_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('is_customer_facing', sa.Boolean(), nullable=True),
    sa.Column('default_export_format', sa.String(), nullable=True),
    sa.Column('default_detail_level', sa.String(), nullable=True),
    sa.Column('branding_config', sa.JSON(), nullable=True),
    sa.Column('cover_page_config', sa.JSON(), nullable=True),
    sa.Column('introduction_text', sa.Text(), nullable=True),
    sa.Column('methodology_text', sa.Text(), nullable=True),
    sa.Column('disclaimer_text', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('default_finding_categories', sa.JSON(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_template_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('section_key', sa.String(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('section_type', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('custom_text', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_template_sections')
    op.drop_table('report_templates')
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_reports_policy_id'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_generated_at'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_customer_id'))

    op.drop_table('generated_reports')
    # ### end Alembic commands ###
