export const FINDING_TYPE_LABELS: Record<string, string> = {
  any_to_any_allow: 'Any-to-Any Allow',
  overly_permissive: 'Overly Permissive',
  duplicate_rule: 'Duplicate Rule',
  redundant_rule: 'Redundant Rule',
  shadowed_rule: 'Shadowed Rule',
  same_action_shadowed_rule: 'Redundant Rule',
  conflicting_shadowed_rule: 'Conflicting Shadowed Rule',
  partial_shadowed_rule: 'Partially Shadowed Rule',
  shadowing_not_evaluated: 'Shadowing Not Evaluated',
  disabled_rule: 'Disabled Rule',
  zero_hit_rule: 'Zero Hits',
  low_usage_rule: 'Low Usage',
  risky_service: 'Risky Service',
  no_logging: 'No Logging',
  no_documentation: 'No Documentation',
  temporary_rule: 'Temporary Rule',
  inoperative_rule: 'Inoperative Rule',
  rule_without_app_controls: 'No App Controls',
  palo_alto_port_based_rule_candidate: 'Port-Based Rule',
  risky_application_allowed: 'Risky Application',
  fortigate_security_profile_gap: 'No Security Profiles',
  application_analysis_not_supported_for_vendor: 'App Analysis Not Supported',
  application_data_unavailable: 'Application Data Unavailable',
  detector_prerequisites_unmet: 'Limited by Missing Data',
  naming_quality: 'Poor Rule Name',
  expired_rule: 'Expired Schedule',
  nat_complexity: 'NAT Rule',
  vpn_access: 'Broad VPN Access',
  negated_object: 'Negated Object',
  rdp_exposed: 'RDP Exposed',
  ssh_exposed: 'SSH Exposed',
  database_exposed: 'Database Exposed',
  cleartext_service: 'Cleartext Protocol',
  inbound_from_internet: 'Inbound From Internet',
  lateral_movement_risk: 'Lateral Movement Risk',
  mergeable_rules: 'Consolidation Candidate',
  no_cleanup_rule: 'Missing Cleanup Rule',
  rule_order_optimization: 'Rule Order Optimization',
  large_rule_section: 'Oversized Section',
  unattached_object: 'Unattached Object',
  object_usage_unknown: 'Object Usage Unknown',
  unused_object: 'Unused Object',
  duplicate_object: 'Duplicate Object',
  overlapping_object: 'Overlapping Object',
  empty_group: 'Empty Group',
  large_group: 'Large Group',
  broad_network: 'Broad Network',
  service_range: 'Large Port Range',
  import_quality: 'Import Quality',
  analysis_configuration: 'Analysis Configuration',
  // Version intelligence
  version_outdated: 'Version Outdated',
  version_end_of_support: 'End of Support',
  version_catalog_unavailable: 'Version Catalog N/A',
  version_ha_mismatch: 'HA Version Mismatch',
  version_unknown: 'Unknown Version',
  // NAT & public exposure (nat_exposure / interfaces analyzers)
  nat_public_to_internal: 'NAT: Public to Internal',
  nat_static: 'Static NAT Mapping',
  nat_source: 'Source / Hide NAT',
  nat_duplicate: 'Duplicate NAT Rule',
  nat_overlap: 'Overlapping NAT Rules',
  nat_without_policy: 'NAT Without Security Policy',
  policy_without_nat: 'Inbound Rule Without NAT',
  rdp_public_exposure: 'RDP Publicly Exposed',
  ssh_public_exposure: 'SSH Publicly Exposed',
  telnet_public_exposure: 'Telnet Publicly Exposed',
  smb_public_exposure: 'SMB Publicly Exposed',
  winrm_public_exposure: 'WinRM Publicly Exposed',
  vnc_public_exposure: 'VNC Publicly Exposed',
  database_public_exposure: 'Database Publicly Exposed',
  any_service_public_exposure: 'Any-Service Public Exposure',
  sensitive_destination_exposure: 'Sensitive Host Exposed',
  public_exposure_no_logging: 'Unlogged Public Exposure',
  mgmt_on_public_interface: 'Mgmt on Public Interface',
}

export function findingTypeLabel(type: string): string {
  return FINDING_TYPE_LABELS[type] || type.replace(/_/g, ' ')
}

export function shortFindingTypeLabel(type: string): string {
  const short: Record<string, string> = {
    any_to_any_allow: 'Any/Any',
    overly_permissive: 'Permissive',
    duplicate_rule: 'Dup',
    redundant_rule: 'Redundant',
    shadowed_rule: 'Shadow',
    same_action_shadowed_rule: 'Redundant',
    conflicting_shadowed_rule: 'Conflict',
    partial_shadowed_rule: 'Partial Shadow',
    shadowing_not_evaluated: 'Shadow Skipped',
    zero_hit_rule: 'Zero Hit',
    no_logging: 'No Log',
    risky_service: 'Risky Svc',
    temporary_rule: 'Temp',
    detector_prerequisites_unmet: 'Data Limited',
    import_quality: 'Import',
  }
  return short[type] || findingTypeLabel(type)
}

export const SHADOW_FINDING_TYPES = new Set([
  'shadowed_rule',
  'redundant_rule',
  'same_action_shadowed_rule',
  'conflicting_shadowed_rule',
  'partial_shadowed_rule',
])
